// Autogenerated by Nightwatch
// Refer to the online docs for more details: https://nightwatchjs.org/gettingstarted/configuration/
const Services = {};
loadServices();

module.exports = {
  src_folders: ["e2e"],
  globals_path: "nightwatch.globals.js",

  webdriver: {},

  test_settings: {
    default: {
      disable_error_log: false,
      launch_url: "localhost:3002",

      screenshots: {
        enabled: false,
        path: "screens",
        on_failure: true
      },

      desiredCapabilities: {
        browserName: "chrome",
        chromeOptions: {
          // This tells Chromedriver to run using the legacy JSONWire protocol (not required in Chrome 78)
          // w3c: false,
          // More info on Chromedriver: https://sites.google.com/a/chromium.org/chromedriver/
          args: [
            //'--no-sandbox',
            //'--ignore-certificate-errors',
            //'--allow-insecure-localhost',
            //'--headless'
          ]
        }
      },

      webdriver: {
        start_process: true,
        port: 9515,
        server_path: Services.chromedriver ? Services.chromedriver.path : "",
        cli_args: [
          // --verbose
        ]
      }
    },
  }
};

function loadServices() {
  try {
    Services.chromedriver = require("chromedriver");
  } catch (err) {}
}
